import type { TokenCharacteristics } from './tokenCreationTypes';

/**
 * Common token definitions for quick creation.
 */
export const COMMON_TOKENS: Record<string, TokenCharacteristics> = {
  // Artifact tokens
  'Treasure': {
    name: 'Treasure',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Treasure'],
    abilities: ['{T}, Sacrifice this artifact: Add one mana of any color.'],
    isArtifact: true,
  },
  'Gold': {
    name: 'Gold',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Gold'],
    abilities: ['Sacrifice this token: Add one mana of any color.'],
    isArtifact: true,
  },
  'Food': {
    name: 'Food',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Food'],
    abilities: ['{2}, {T}, Sacrifice this artifact: You gain 3 life.'],
    isArtifact: true,
  },
  'Clue': {
    name: 'Clue',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Clue'],
    abilities: ['{2}, Sacrifice this artifact: Draw a card.'],
    isArtifact: true,
  },
  'Blood': {
    name: 'Blood',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Blood'],
    abilities: ['{1}, {T}, Discard a card, Sacrifice this artifact: Draw a card.'],
    isArtifact: true,
  },
  'Junk': {
    name: 'Junk',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Junk'],
    abilities: ['{T}, Sacrifice this artifact: Exile the top card of your library. You may play that card this turn. Activate only as a sorcery.'],
    isArtifact: true,
  },
  'Map': {
    name: 'Map',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Map'],
    abilities: ['{1}, {T}, Sacrifice this artifact: Target creature you control explores.'],
    isArtifact: true,
  },
  'Incubator': {
    name: 'Incubator',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Incubator'],
    abilities: ['{2}: Transform this artifact.'],
    isArtifact: true,
  },
  'Lander': {
    name: 'Lander',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Lander'],
    abilities: ['{2}, {T}, Sacrifice this token: Search your library for a basic land card, put it onto the battlefield tapped, then shuffle.'],
    isArtifact: true,
  },
  'Mutagen': {
    name: 'Mutagen',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Mutagen'],
    abilities: ['{1}, {T}, Sacrifice this token: Put a +1/+1 counter on target creature. Activate only as a sorcery.'],
    isArtifact: true,
  },
  'Powerstone': {
    name: 'Powerstone',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Powerstone'],
    abilities: ['{T}: Add {C}. This mana can\'t be spent to cast a nonartifact spell.'],
    isArtifact: true,
  },
  'Vehicle': {
    name: 'Vehicle',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Vehicle'],
    power: 3,
    toughness: 2,
    abilities: ['Crew 1 (Tap any number of creatures you control with total power 1 or more: This token becomes an artifact creature until end of turn.)'],
    isArtifact: true,
  },
  'Nalaar Aetherjet': {
    name: 'Nalaar Aetherjet',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Vehicle'],
    abilities: ['Flying', 'Crew 2 (Tap any number of creatures you control with total power 2 or more: This token becomes an artifact creature until end of turn.)'],
    isArtifact: true,
  },
  'Rock': {
    name: 'Rock',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Equipment'],
    abilities: ['Equipped creature has "{1}, {T}, Sacrifice Rock: This creature deals 2 damage to any target."', 'Equip {1}'],
    isArtifact: true,
  },
  'Sword': {
    name: 'Sword',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Equipment'],
    abilities: ['Equipped creature gets +1/+1', 'Equip {2}'],
    isArtifact: true,
  },
  'Stoneforged Blade': {
    name: 'Stoneforged Blade',
    colors: [],
    types: ['Artifact'],
    subtypes: ['Equipment'],
    abilities: ['Indestructible', 'Equipped creature gets +5/+5 and has double strike.', 'Equip {0}'],
    isArtifact: true,
  },

  // Common creature tokens
  '1/1 Soldier': {
    name: 'Soldier',
    colors: ['W'],
    types: ['Creature'],
    subtypes: ['Soldier'],
    power: 1,
    toughness: 1,
    abilities: [],
  },
  '1/1 Spirit (Flying)': {
    name: 'Spirit',
    colors: ['W'],
    types: ['Creature'],
    subtypes: ['Spirit'],
    power: 1,
    toughness: 1,
    abilities: ['Flying'],
  },
  '2/2 Zombie': {
    name: 'Zombie',
    colors: ['B'],
    types: ['Creature'],
    subtypes: ['Zombie'],
    power: 2,
    toughness: 2,
    abilities: [],
  },
  '1/1 Goblin': {
    name: 'Goblin',
    colors: ['R'],
    types: ['Creature'],
    subtypes: ['Goblin'],
    power: 1,
    toughness: 1,
    abilities: [],
  },
  '3/3 Beast': {
    name: 'Beast',
    colors: ['G'],
    types: ['Creature'],
    subtypes: ['Beast'],
    power: 3,
    toughness: 3,
    abilities: [],
  },
  '1/1 Saproling': {
    name: 'Saproling',
    colors: ['G'],
    types: ['Creature'],
    subtypes: ['Saproling'],
    power: 1,
    toughness: 1,
    abilities: [],
  },
  '1/1 Thopter (Flying)': {
    name: 'Thopter',
    colors: [],
    types: ['Artifact', 'Creature'],
    subtypes: ['Thopter'],
    power: 1,
    toughness: 1,
    abilities: ['Flying'],
    isArtifact: true,
  },
  '1/1 Servo': {
    name: 'Servo',
    colors: [],
    types: ['Artifact', 'Creature'],
    subtypes: ['Servo'],
    power: 1,
    toughness: 1,
    abilities: [],
    isArtifact: true,
  },
  '4/4 Angel (Flying)': {
    name: 'Angel',
    colors: ['W'],
    types: ['Creature'],
    subtypes: ['Angel'],
    power: 4,
    toughness: 4,
    abilities: ['Flying'],
  },
  '5/5 Dragon (Flying)': {
    name: 'Dragon',
    colors: ['R'],
    types: ['Creature'],
    subtypes: ['Dragon'],
    power: 5,
    toughness: 5,
    abilities: ['Flying'],
  },
  '2/2 Wolf': {
    name: 'Wolf',
    colors: ['G'],
    types: ['Creature'],
    subtypes: ['Wolf'],
    power: 2,
    toughness: 2,
    abilities: [],
  },
  '1/1 Human': {
    name: 'Human',
    colors: ['W'],
    types: ['Creature'],
    subtypes: ['Human'],
    power: 1,
    toughness: 1,
    abilities: [],
  },
  '1/1 Warrior': {
    name: 'Warrior',
    colors: ['R'],
    types: ['Creature'],
    subtypes: ['Warrior'],
    power: 1,
    toughness: 1,
    abilities: [],
    entersTapped: true,
  },
  '1/1 Faerie Rogue (Flying)': {
    name: 'Faerie Rogue',
    colors: ['B'],
    types: ['Creature'],
    subtypes: ['Faerie', 'Rogue'],
    power: 1,
    toughness: 1,
    abilities: ['Flying'],
  },
  '0/1 Eldrazi Spawn': {
    name: 'Eldrazi Spawn',
    colors: [],
    types: ['Creature'],
    subtypes: ['Eldrazi', 'Spawn'],
    power: 0,
    toughness: 1,
    abilities: ['Sacrifice this creature: Add {C}.'],
  },
  '1/1 Eldrazi Scion': {
    name: 'Eldrazi Scion',
    colors: [],
    types: ['Creature'],
    subtypes: ['Eldrazi', 'Scion'],
    power: 1,
    toughness: 1,
    abilities: ['Sacrifice this creature: Add {C}.'],
  },
  '0/1 Plant': {
    name: 'Plant',
    colors: ['G'],
    types: ['Creature'],
    subtypes: ['Plant'],
    power: 0,
    toughness: 1,
    abilities: [],
  },
  '1/1 Elf Warrior': {
    name: 'Elf Warrior',
    colors: ['G'],
    types: ['Creature'],
    subtypes: ['Elf', 'Warrior'],
    power: 1,
    toughness: 1,
    abilities: [],
  },
  '1/1 Soldier (Haste)': {
    name: 'Soldier',
    colors: ['R', 'W'],
    types: ['Creature'],
    subtypes: ['Soldier'],
    power: 1,
    toughness: 1,
    abilities: ['Haste'],
  },
  '1/1 Cat': {
    name: 'Cat',
    colors: ['W'],
    types: ['Creature'],
    subtypes: ['Cat'],
    power: 1,
    toughness: 1,
    abilities: [],
  },
  '1/1 Snake': {
    name: 'Snake',
    colors: ['G'],
    types: ['Creature'],
    subtypes: ['Snake'],
    power: 1,
    toughness: 1,
    abilities: [],
  },
  '1/1 Bird (Flying)': {
    name: 'Bird',
    colors: ['W'],
    types: ['Creature'],
    subtypes: ['Bird'],
    power: 1,
    toughness: 1,
    abilities: ['Flying'],
  },
  '3/1 Elemental (Trample, Haste)': {
    name: 'Elemental',
    colors: ['R'],
    types: ['Creature'],
    subtypes: ['Elemental'],
    power: 3,
    toughness: 1,
    abilities: ['Trample', 'Haste'],
  },
  '1/1 Insect': {
    name: 'Insect',
    colors: ['G'],
    types: ['Creature'],
    subtypes: ['Insect'],
    power: 1,
    toughness: 1,
    abilities: [],
  },
  '6/6 Wurm (Trample)': {
    name: 'Wurm',
    colors: ['G'],
    types: ['Creature'],
    subtypes: ['Wurm'],
    power: 6,
    toughness: 6,
    abilities: ['Trample'],
  },
  '1/1 Squirrel': {
    name: 'Squirrel',
    colors: ['G'],
    types: ['Creature'],
    subtypes: ['Squirrel'],
    power: 1,
    toughness: 1,
    abilities: [],
  },
  '1/1 Merfolk (Hexproof)': {
    name: 'Merfolk',
    colors: ['U'],
    types: ['Creature'],
    subtypes: ['Merfolk'],
    power: 1,
    toughness: 1,
    abilities: ['Hexproof'],
  },
};

export function getCommonTokenNames(): readonly string[] {
  return Object.keys(COMMON_TOKENS);
}

export function getTokenCharacteristics(name: string): TokenCharacteristics | undefined {
  return COMMON_TOKENS[name];
}
