/**
 * Provoke keyword ability implementation (Rule 702.39)
 * 
 * @see MagicCompRules 702.39
 */

/**
 * Provoke ability interface
 * Rule 702.39a: "Provoke" means "Whenever this creature attacks, you may choose to have target creature
 * defending player controls block this creature this combat if able. If you do, untap that creature."
 */
export interface ProvokeAbility {
  readonly type: 'provoke';
  readonly source: string;
  readonly targetCreature?: string;
  readonly wasTriggered: boolean;
}

export interface ProvokeSummary {
  readonly source: string;
  readonly targetCreature?: string;
  readonly wasTriggered: boolean;
  readonly mustBlock: boolean;
  readonly untapTarget: boolean;
}

/**
 * Creates a Provoke ability
 * 
 * @param source - The source creature ID
 * @returns ProvokeAbility object
 */
export function provoke(source: string): ProvokeAbility {
  return {
    type: 'provoke',
    source,
    wasTriggered: false,
  };
}

/**
 * Triggers provoke ability when attacking
 * 
 * @param ability - The provoke ability
 * @param targetCreature - The creature to provoke (optional)
 * @returns Updated ProvokeAbility
 */
export function triggerProvoke(
  ability: ProvokeAbility,
  targetCreature?: string
): ProvokeAbility {
  return {
    ...ability,
    targetCreature,
    wasTriggered: true,
  };
}

/**
 * Checks if a creature must block due to provoke
 * 
 * @param ability - The provoke ability
 * @param creatureId - The creature to check
 * @returns True if this creature must block if able
 */
export function mustBlockIfAble(ability: ProvokeAbility, creatureId: string): boolean {
  return ability.targetCreature === creatureId && ability.wasTriggered;
}

/**
 * Checks whether a creature is a legal provoke target.
 *
 * @param source - The attacking creature with provoke
 * @param targetCreature - The potential blocker to provoke
 * @param defendingPlayerControlsCreature - Whether the defending player controls the target creature
 * @param targetCanBlock - Whether the target creature can legally block the attacker
 * @returns True if the target can be chosen for provoke
 */
export function canProvokeTarget(
  source: string,
  targetCreature: string | undefined,
  defendingPlayerControlsCreature: boolean,
  targetCanBlock: boolean
): boolean {
  return Boolean(
    targetCreature
    && targetCreature !== source
    && defendingPlayerControlsCreature
    && targetCanBlock
  );
}

/**
 * Creates the combat requirement generated by provoke.
 *
 * @param ability - The provoke ability
 * @returns Combat requirement data, or null if no valid requirement exists
 */
export function createProvokeRequirement(ability: ProvokeAbility): {
  source: string;
  targetCreature: string;
  mustBlock: true;
  untapTarget: true;
} | null {
  if (!ability.wasTriggered || !ability.targetCreature) {
    return null;
  }

  return {
    source: ability.source,
    targetCreature: ability.targetCreature,
    mustBlock: true,
    untapTarget: true,
  };
}

/**
 * Checks if provoke abilities are redundant
 * Rule 702.39b: If a creature has multiple instances of provoke, each triggers separately
 * 
 * @returns False - provoke instances are never redundant
 */
export function isProvokeRedundant(): boolean {
  return false; // Rule 702.39b: Each instance triggers separately
}

export function createProvokeSummary(ability: ProvokeAbility): ProvokeSummary {
  const requirement = createProvokeRequirement(ability);

  return {
    source: ability.source,
    targetCreature: ability.targetCreature,
    wasTriggered: ability.wasTriggered,
    mustBlock: requirement?.mustBlock ?? false,
    untapTarget: requirement?.untapTarget ?? false,
  };
}
